---

# REVIEW: it is kind of a chore to have to install `setuptools`
#         just to get `easy_install` and use it to fetch the latest
#         `pip` (which is way newer than the distro `python-pip`).
#
#         Could we default on the distro pip? Does that conflict
#         with an easy_installed pip later on? Could we just assume
#         that pip is installed and carry on?

- name: Prerequisites for provisioning (setuptools and pydev)
  sudo: yes
  apt:
    name: "{{item}}"
  with_items:
    - python-setuptools
    - python-dev
  tags:
    - nginx
    - frontend
    - python
    - dev
    - deps

- name: Prerequisites for provisioning (pip)
  sudo: yes
  easy_install:
    name: pip
  tags:
    - nginx
    - frontend
    - python
    - deps

- name: Prerequisites for provisioning (libcurl-dev)
  sudo: yes
  apt:
    name: "{{item}}"
  with_items:
    - build-essential
    - libcurl4-openssl-dev
  tags:
    - nginx
    - frontend
    - dev
    - deps

- name: Prerequisites for provisioning (pycurl)
  sudo: yes
  pip:
    name: pycurl
  tags:
    - nginx
    - frontend
    - python
    - deps
